In [1]:
!pip3 install keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import heapq
import pandas as pd
import keras

from nltk.tokenize import RegexpTokenizer
from keras.models import Sequential, load_model
from keras.layers import LSTM
from keras.layers.core import Dense, Activation
from tensorflow.keras.optimizers import RMSprop
from sklearn.model_selection import train_test_split
from keras.datasets import mnist
from keras.models import Model, Sequential
from keras.layers import Input, Dense
from keras.utils import np_utils
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from sklearn.preprocessing import MinMaxScaler
from keras.utils import np_utils
from keras import backend as K
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [4]:
TNet=pd.read_csv('taipeiD_TNet2.csv',header=None)

In [5]:
TNet.head()

0         1         2         3         4         5         6   \
0  0.017943  0.005415  0.003590  0.008316  0.007859  0.012942  0.012196   
1  0.021283  0.005215  0.003530  0.009359  0.007803  0.014288  0.011185   
2  0.028988  0.006511  0.005591  0.012970  0.007816  0.015878  0.010973   
3  0.029534  0.006471  0.005615  0.013017  0.007717  0.016098  0.011182   
4  0.029333  0.006525  0.005727  0.013098  0.007692  0.016358  0.011000   

         7         8         9   ...        90        91        92        93  \
0  0.019543  0.001196  0.003327  ...  0.002529  0.001533  0.001860  0.002375   
1  0.019044  0.001383  0.003499  ...  0.002803  0.001757  0.001783  0.002549   
2  0.015768  0.002252  0.005388  ...  0.004649  0.002555  0.002672  0.004291   
3  0.015815  0.002325  0.005443  ...  0.004611  0.002473  0.002635  0.004195   
4  0.015677  0.002344  0.005527  ...  0.004694  0.002515  0.002677  0.004222   

         94        95        96        97        98        99  
0  0.005408  0.008922  0.003945  0.011075  0.005073  0.012708  
1  0.005515  0.009650  0.003596  0.009618  0.005946  0.013709  
2  0.007385  0.009558  0.004293  0.008791  0.010040  0.016301  
3  0.007255  0.009487  0.004316  0.008729  0.010296  0.016437  
4  0.007269  0.009921  0.004387  0.008923  0.010381  0.016914  

[5 rows x 100 columns]

In [6]:
#convert to an array and scale the data
X=np.array(TNet);

In [7]:
X=MinMaxScaler(feature_range=(0, 1), copy=True).fit_transform(X)

In [8]:
X.shape

(669, 100)

In [9]:
y=np.array(range(669))%7; y[:10]

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [10]:
yc=np_utils.to_categorical(y) #get categorical binary variables isSunday, isMonday,...
yc[:5]

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [11]:
X_test=X[400:,:]; X_train=X[:400,:]; #split the data into training and test
y_test=yc[400:,:]; y_train=yc[:400,:]

In [12]:
y_test

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
for i in range(len(y)):
  if (y[i] == 0 )or( y[i] == 6):
    y[i] = 1.
  else:
    y[i] = 0.

In [14]:
y_test = y[400:] 
y_train = y[:400]

In [15]:
np.random.seed(2019)
model = Sequential()
model.add(Dense(30, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['categorical_accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=20)
predict = model.predict(X_test)

Epoch 1/100
20/20 [==============================] - 3s 27ms/step - loss: 0.6820 - categorical_accuracy: 1.0000 - val_loss: 0.6533 - val_categorical_accuracy: 1.0000
Epoch 2/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6318 - categorical_accuracy: 1.0000 - val_loss: 0.6066 - val_categorical_accuracy: 1.0000
Epoch 3/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5887 - categorical_accuracy: 1.0000 - val_loss: 0.5726 - val_categorical_accuracy: 1.0000
Epoch 4/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5638 - categorical_accuracy: 1.0000 - val_loss: 0.5553 - val_categorical_accuracy: 1.0000
Epoch 5/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5486 - categorical_accuracy: 1.0000 - val_loss: 0.5442 - val_categorical_accuracy: 1.0000
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5365 - categorical_accuracy: 1.0000 - val_loss: 0.5340 - val_categorical_accuracy: 1.0000
Epoch 7/

In [16]:
# categorizing the day of the week
y=np.array(range(669))%7; y[:10]
yc=np_utils.to_categorical(y) #get categorical binary variables isSunday, isMonday,...
yc[:5]
X_test=X[400:,:]; X_train=X[:400,:]; #split the data into training and test
y_test=yc[400:,:]; y_train=yc[:400,:]


np.random.seed(2019)
model = Sequential()
model.add(Dense(30, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(15, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(7, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['categorical_accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=200, batch_size=20)
predict = model.predict(X_test)

Epoch 1/200
20/20 [==============================] - 1s 11ms/step - loss: 0.6874 - categorical_accuracy: 0.1375 - val_loss: 0.6711 - val_categorical_accuracy: 0.1004
Epoch 2/200
20/20 [==============================] - 0s 4ms/step - loss: 0.6614 - categorical_accuracy: 0.0775 - val_loss: 0.6534 - val_categorical_accuracy: 0.0186
Epoch 3/200
20/20 [==============================] - 0s 4ms/step - loss: 0.6438 - categorical_accuracy: 0.0450 - val_loss: 0.6363 - val_categorical_accuracy: 0.0186
Epoch 4/200
20/20 [==============================] - 0s 4ms/step - loss: 0.6266 - categorical_accuracy: 0.0900 - val_loss: 0.6184 - val_categorical_accuracy: 0.0483
Epoch 5/200
20/20 [==============================] - 0s 4ms/step - loss: 0.6083 - categorical_accuracy: 0.1100 - val_loss: 0.5998 - val_categorical_accuracy: 0.0223
Epoch 6/200
20/20 [==============================] - 0s 4ms/step - loss: 0.5891 - categorical_accuracy: 0.1125 - val_loss: 0.5832 - val_categorical_accuracy: 0.0223
Epoch 7/2